INSERT INTO ARMOUR ("ARMOUR_ID", "OWNER", "NAME", "ARMOUR_BONUS", "GOLD", "SILVER", "COPPER", "DESCRIPTION") VALUES ('1239', '1', 'CHEST OF MIGHT', '3', '10', '10', '0', 'LOREM IPSUM');
INSERT INTO ARMOUR ("ARMOUR_ID", "OWNER", "NAME", "ARMOUR_BONUS", "GOLD", "SILVER", "COPPER", "DESCRIPTION") VALUES ('5454', '2', 'CHEST OF FROST', '3', '10', '10', '0', 'LOREM IPSUM');
INSERT INTO ARMOUR ("ARMOUR_ID", "OWNER", "NAME", "ARMOUR_BONUS", "GOLD", "SILVER", "COPPER", "DESCRIPTION") VALUES ('3332', '3', 'CLOAK OF FIRE', '4', '300', '80', '0', 'LOREM IPSUM');
INSERT INTO ARMOUR ("ARMOUR_ID", "OWNER", "NAME", "ARMOUR_BONUS", "GOLD", "SILVER", "COPPER", "DESCRIPTION") VALUES ('1354', '4', 'SABATON OF AWESOME', '10', '3000', '80', '0', 'LOREM IPSUM');
INSERT INTO ARMOUR ("ARMOUR_ID", "OWNER", "NAME", "ARMOUR_BONUS", "GOLD", "SILVER", "COPPER", "DESCRIPTION") VALUES ('3466', '5', 'SHOULDER OF ULTIMA', '18', '20000', '0', '0', 'LOREM IPSUM');
