INSERT INTO CLASS ("PLAYER_NO", "CLASS") VALUES ('3', 'RANGER');
INSERT INTO CLASS ("PLAYER_NO", "CLASS") VALUES ('3', 'ROUGE');
INSERT INTO CLASS ("PLAYER_NO", "CLASS") VALUES ('1', 'BARBARIAN');
INSERT INTO CLASS ("PLAYER_NO", "CLASS") VALUES ('2', 'WIZARD');
INSERT INTO CLASS ("PLAYER_NO", "CLASS") VALUES ('4', 'MAGE');
INSERT INTO CLASS ("PLAYER_NO", "CLASS") VALUES ('5', 'WIZARD');
INSERT INTO CLASS ("PLAYER_NO", "CLASS") VALUES ('5', 'BARBARIAN');
