INSERT INTO COMPONENT ("SPELL_ID", "COMPONENT") VALUES ('1222', 'BAY LEAF');
INSERT INTO COMPONENT ("SPELL_ID", "COMPONENT") VALUES ('1456', 'VERBAL');
INSERT INTO COMPONENT ("SPELL_ID", "COMPONENT") VALUES ('9876', 'VERBAL');
INSERT INTO COMPONENT ("SPELL_ID", "COMPONENT") VALUES ('4578', 'NEWTS EYE');
INSERT INTO COMPONENT ("SPELL_ID", "COMPONENT") VALUES ('1222', 'VERBAL');
INSERT INTO COMPONENT ("SPELL_ID", "COMPONENT") VALUES ('1222', 'CLOAK');
INSERT INTO COMPONENT ("SPELL_ID", "COMPONENT") VALUES ('9876', 'WAND');
