

INSERT INTO DUNGEON ("DUNGEON_NO", "NAME", "CHALLENGE_RATING", "AREA") VALUES ('2', 'THE DEVILS PLAYGROUND', '9', 'HELL');
INSERT INTO DUNGEON ("DUNGEON_NO", "NAME", "CHALLENGE_RATING", "AREA") VALUES ('3', 'SECRET KEEPER', '16', 'GROTTO');
INSERT INTO DUNGEON ("DUNGEON_NO", "NAME", "CHALLENGE_RATING", "AREA") VALUES ('4', 'DRAGONS LAIR', '25', 'DEVILS BISCUIT');
INSERT INTO DUNGEON ("DUNGEON_NO", "NAME", "CHALLENGE_RATING", "AREA") VALUES ('5', 'MOLTEN CORE', '10', 'BADLANDS');
INSERT INTO DUNGEON ("DUNGEON_NO", "NAME", "CHALLENGE_RATING", "AREA") VALUES ('1', 'NOOB LAND', '2', 'LOWLANDS');
