INSERT INTO KNOWS_SPELL ("PLAYER_NO", "SPELL_ID") VALUES ('4', '1222');
INSERT INTO KNOWS_SPELL ("PLAYER_NO", "SPELL_ID") VALUES ('5', '1456');
INSERT INTO KNOWS_SPELL ("PLAYER_NO", "SPELL_ID") VALUES ('4', '8877');
INSERT INTO KNOWS_SPELL ("PLAYER_NO", "SPELL_ID") VALUES ('5', '9876');
INSERT INTO KNOWS_SPELL ("PLAYER_NO", "SPELL_ID") VALUES ('5', '4578');
