INSERT INTO SPELL_DAMAGE ("SPELL_ID", "DAMAGE_TYPE") VALUES ('1456', 'FIRE');
INSERT INTO SPELL_DAMAGE ("SPELL_ID", "DAMAGE_TYPE") VALUES ('8877', 'LIGHTNING');
INSERT INTO SPELL_DAMAGE ("SPELL_ID", "DAMAGE_TYPE") VALUES ('9876', 'NATURE');
INSERT INTO SPELL_DAMAGE ("SPELL_ID", "DAMAGE_TYPE") VALUES ('4578', 'ULTIMATE');
INSERT INTO SPELL_DAMAGE ("SPELL_ID", "DAMAGE_TYPE") VALUES ('4578', 'NATURE');
