INSERT INTO SPELL ("SPELL_ID", "NAME", "DAMAGE_VALUE", "DURATION", "RANGE", "CAST_TIME") VALUES ('1222', 'INVISIBILITY', '0', '180', '0', '5');
INSERT INTO SPELL ("SPELL_ID", "NAME", "DAMAGE_VALUE", "DURATION", "RANGE", "CAST_TIME") VALUES ('1456', 'FIREBALL', '60', '1', '40', '10');
INSERT INTO SPELL ("SPELL_ID", "NAME", "DAMAGE_VALUE", "DURATION", "RANGE", "CAST_TIME") VALUES ('8877', 'LIGHTNING BOLT', '10', '1', '70', '0');
INSERT INTO SPELL ("SPELL_ID", "NAME", "DAMAGE_VALUE", "DURATION", "RANGE", "CAST_TIME") VALUES ('9876', 'WISH', '2000', '60', '0', '120');
INSERT INTO SPELL ("SPELL_ID", "NAME", "DAMAGE_VALUE", "DURATION", "RANGE", "CAST_TIME") VALUES ('4578', 'ULTIMA', '100', '1', '10', '10');
