INSERT INTO WEAPON_DAMAGE ("WEAPON_ID", "DAMGE_TYPE") VALUES ('2', 'SLASHING');
INSERT INTO WEAPON_DAMAGE ("WEAPON_ID", "DAMGE_TYPE") VALUES ('2', 'PIERCING');
INSERT INTO WEAPON_DAMAGE ("WEAPON_ID", "DAMGE_TYPE") VALUES ('4', 'FROST');
INSERT INTO WEAPON_DAMAGE ("WEAPON_ID", "DAMGE_TYPE") VALUES ('4', 'BLUNT');
INSERT INTO WEAPON_DAMAGE ("WEAPON_ID", "DAMGE_TYPE") VALUES ('5', 'ULTIMA');
INSERT INTO WEAPON_DAMAGE ("WEAPON_ID", "DAMGE_TYPE") VALUES ('3', 'PIERCING');
INSERT INTO WEAPON_DAMAGE ("WEAPON_ID", "DAMGE_TYPE") VALUES ('1', 'FIRE');
INSERT INTO WEAPON_DAMAGE ("WEAPON_ID", "DAMGE_TYPE") VALUES ('1', 'BLUNT');
