INSERT INTO WEAPON ("WEAPON_ID", "OWNER", "NAME", "DAMAGE_VALUE", "GOLD", "SILVER", "COPPER", "DESCRIPTION") VALUES ('1230', '1', 'STAFF OF SNAKES', '10', '0', '10', '0', 'LOREM IPSUM');
INSERT INTO WEAPON ("WEAPON_ID", "OWNER", "NAME", "DAMAGE_VALUE", "GOLD", "SILVER", "COPPER", "DESCRIPTION") VALUES ('3390', '2', 'GREAT SWORD OF MANN', '30', '1', '10', '0', 'LOREM IPSUM');
INSERT INTO WEAPON ("WEAPON_ID", "OWNER", "NAME", "DAMAGE_VALUE", "GOLD", "SILVER", "COPPER", "DESCRIPTION") VALUES ('1730', '3', 'BOW OF MIGHT', '25', '10', '10', '0', 'LOREM IPSUM');
INSERT INTO WEAPON ("WEAPON_ID", "OWNER", "NAME", "DAMAGE_VALUE", "GOLD", "SILVER", "COPPER", "DESCRIPTION") VALUES ('4599', '4', 'STAFF OF THE KING', '80', '200', '1', '10', 'LOREM IPSUM');
INSERT INTO WEAPON ("WEAPON_ID", "OWNER", "NAME", "DAMAGE_VALUE", "GOLD", "SILVER", "COPPER", "DESCRIPTION") VALUES ('1000', '5', 'GREAT STAFF OF THE AMAZING DYLAN', '100', '1000000', '0', '0', 'LOREM IPSUM');
